/* One-off helper: inlines assets/books/*.md into src/lib/_book_sources.ts so the
 * sample book is bundled as a JS string (no runtime file-system read needed).
 * Usage: node tools/gen_books.js
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const booksDir = path.join(root, 'assets', 'books');
const out = path.join(root, 'src', 'lib', '_book_sources.ts');

const files = fs.readdirSync(booksDir).filter((f) => f.endsWith('.md'));
if (!files.length) {
  console.error('No .md books found in assets/books/');
  process.exit(1);
}

let code = '// Auto-generated by tools/gen_books.js. Do not edit by hand.\n';
for (const f of files) {
  const slug = f.replace(/\.md$/, '');
  const name = slug.toUpperCase().replace(/[^A-Z0-9]/g, '_') + '_SOURCE';
  const content = fs.readFileSync(path.join(booksDir, f), 'utf8');
  code += `export const ${name} = ${JSON.stringify(content)};\n`;
}

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, code, 'utf8');
console.log(`Generated ${path.relative(root, out)} for: ${files.join(', ')}`);
